//! Auto-generated stubs for libxml2 symbols that lxml (and other
//! consumers) reference at load time, but our shim doesn't yet
//! implement.
//!
//! Regenerated by `tests/abi-system/lxml/regen_stubs.sh` from
//! `tests/abi-system/lxml/target_symbols.txt`.  Do not edit by hand —
//! re-run the script after adding symbols to the canonical list.
//!
//! # Why every stub returns `*mut c_void`
//!
//! At load time, dyld only checks symbol *names*; signatures aren't
//! part of the linkage contract.  At runtime, the System V x86_64 /
//! AAPCS aarch64 calling conventions pass arguments in caller-saved
//! registers, so a no-arg stub can be called with any argument list
//! without corrupting state — the args just sit in registers we
//! ignore.  Return value goes in `rax`/`x0`, and `NULL` (0) is the
//! same bit pattern in every pointer or integer return type the
//! caller might interpret.
//!
//! Net effect: `import lxml` succeeds.  Any actual *use* of a stubbed
//! function gets NULL back and lxml's error-checking takes over —
//! typically raising a Python exception.

#![allow(non_snake_case)]

use std::os::raw::{c_int, c_void};
use std::ptr;

/// Diagnostic hook.  When `SUPXML_TRACE_STUBS` is set in the
/// environment, every stub call writes its name to stderr — useful
/// when a consumer crashes after calling an unimplemented function
/// and we want to know which one.
#[inline]
fn record_call(name: &'static str) {
    use std::sync::atomic::{AtomicI8, Ordering};
    static TRACE: AtomicI8 = AtomicI8::new(-1);
    let on = match TRACE.load(Ordering::Relaxed) {
        -1 => {
            let on = std::env::var_os("SUPXML_TRACE_STUBS").is_some();
            TRACE.store(if on { 1 } else { 0 }, Ordering::Relaxed);
            on
        }
        1 => true,
        _ => false,
    };
    if on {
        eprintln!("[stub] {name}");
    }
}

// Unused when every target symbol is already implemented (no stubs
// generated below) — that's the healthy state, not a problem.
#[allow(unused_macros)]
macro_rules! stub {
    ($name:ident) => {
        #[unsafe(no_mangle)]
        pub unsafe extern "C" fn $name() -> *mut c_void {
            record_call(stringify!($name));
            ptr::null_mut()
        }
    };
}

// ── thread-safe accessor functions (return pointer into mutable global) ──
//
// libxml2's globals.h has a pattern where each XMLPUBVAR global has a
// matching `__name()` accessor function.  When threading support is
// compiled in (the default on macOS / most distros), the bare global
// name expands to `(*(__name()))` — so the accessor is what shows up
// as an undefined symbol in consumer code.  We back each accessor
// with a zero-initialized storage slot of the right size.

/// libxml2 `_xmlSAXHandlerV1` (parser.h): 27 fn-ptr slots + `initialized: c_uint`
/// + 4 bytes natural padding.  We never read these fields — but our
/// storage must be large enough for callers to address them without
/// running past our allocation.
#[repr(C)]
#[derive(Copy, Clone)]
struct XmlSAXHandlerV1 {
    slots: [*mut c_void; 27],
    initialized: u32,
    _pad: u32,
}
const _: () = {
    assert!(std::mem::size_of::<XmlSAXHandlerV1>() == 224,
            "xmlSAXHandlerV1 must be 224 bytes (27*8 + 4 + 4 pad)");
};

static mut HTML_DEFAULT_SAX_HANDLER: XmlSAXHandlerV1 = XmlSAXHandlerV1 {
    slots: [ptr::null_mut(); 27],
    initialized: 0,
    _pad: 0,
};

#[unsafe(no_mangle)]
pub unsafe extern "C" fn __htmlDefaultSAXHandler() -> *mut c_void {
    record_call("__htmlDefaultSAXHandler");
    let addr = &raw mut HTML_DEFAULT_SAX_HANDLER;
    addr as *mut c_void
}

/// libxml2's `__xmlParserVersion()` returns `const xmlChar **`.
/// `xmlParserVersion` is a `const char *` global — the accessor
/// returns a pointer to that global.
static mut XML_PARSER_VERSION: *const u8 =
    b"20913-sup-xml-compat\0".as_ptr();

#[unsafe(no_mangle)]
pub unsafe extern "C" fn __xmlParserVersion() -> *mut c_void {
    record_call("__xmlParserVersion");
    let addr = &raw mut XML_PARSER_VERSION;
    addr as *mut c_void
}

/// `__xmlStructuredError()` returns `xmlStructuredErrorFunc *` —
/// a pointer to a function-pointer global.  We give it a single
/// nullable slot.
static mut XML_STRUCTURED_ERROR: *mut c_void = ptr::null_mut();

#[unsafe(no_mangle)]
pub unsafe extern "C" fn __xmlStructuredError() -> *mut c_void {
    record_call("__xmlStructuredError");
    let addr = &raw mut XML_STRUCTURED_ERROR;
    addr as *mut c_void
}

/// `__xmlStructuredErrorContext()` returns `void **` — a pointer to
/// a `void *` global slot.
static mut XML_STRUCTURED_ERROR_CONTEXT: *mut c_void = ptr::null_mut();

#[unsafe(no_mangle)]
pub unsafe extern "C" fn __xmlStructuredErrorContext() -> *mut c_void {
    record_call("__xmlStructuredErrorContext");
    let addr = &raw mut XML_STRUCTURED_ERROR_CONTEXT;
    addr as *mut c_void
}

/// libxml2's "generic" (printf-style) error reporter, twin of the
/// structured one above.  libxslt registers a handler here during
/// stylesheet parsing — without storage backing the slot, the
/// `xmlSetGenericErrorFunc(...)` call dereferences NULL.
static mut XML_GENERIC_ERROR: *mut c_void = ptr::null_mut();

#[unsafe(no_mangle)]
pub unsafe extern "C" fn __xmlGenericError() -> *mut c_void {
    record_call("__xmlGenericError");
    let addr = &raw mut XML_GENERIC_ERROR;
    addr as *mut c_void
}

/// Context pointer that pairs with the generic-error function above.
/// libxml2 hands it as the first argument to the error callback.
static mut XML_GENERIC_ERROR_CONTEXT: *mut c_void = ptr::null_mut();

#[unsafe(no_mangle)]
pub unsafe extern "C" fn __xmlGenericErrorContext() -> *mut c_void {
    record_call("__xmlGenericErrorContext");
    let addr = &raw mut XML_GENERIC_ERROR_CONTEXT;
    addr as *mut c_void
}

/// `__xmlIndentTreeOutput()` — pointer to the "indent tree output"
/// flag.  Default 1 (indent).  XML::LibXML reads this slot directly.
static mut XML_INDENT_TREE_OUTPUT: c_int = 1;

#[unsafe(no_mangle)]
pub unsafe extern "C" fn __xmlIndentTreeOutput() -> *mut c_void {
    record_call("__xmlIndentTreeOutput");
    let addr = &raw mut XML_INDENT_TREE_OUTPUT;
    addr as *mut c_void
}

/// `__xmlSaveNoEmptyTags()` — pointer to the "save no empty tags"
/// flag.  Default 0 (self-closing `<foo/>` form for empty elements).
static mut XML_SAVE_NO_EMPTY_TAGS: c_int = 0;

#[unsafe(no_mangle)]
pub unsafe extern "C" fn __xmlSaveNoEmptyTags() -> *mut c_void {
    record_call("__xmlSaveNoEmptyTags");
    let addr = &raw mut XML_SAVE_NO_EMPTY_TAGS;
    addr as *mut c_void
}

/// `__xmlDoValidityCheckingDefaultValue()` — pointer to the "validate
/// against DTD by default" flag.  Default 0 (no DTD validation unless
/// explicitly requested).
static mut XML_DO_VALIDITY_CHECKING_DEFAULT: c_int = 0;

#[unsafe(no_mangle)]
pub unsafe extern "C" fn __xmlDoValidityCheckingDefaultValue() -> *mut c_void {
    record_call("__xmlDoValidityCheckingDefaultValue");
    let addr = &raw mut XML_DO_VALIDITY_CHECKING_DEFAULT;
    addr as *mut c_void
}

/// `__xmlLoadExtDtdDefaultValue()` — pointer to the "load external
/// DTDs by default" flag.  Default 0 (XXE-safe; external DTD loading
/// is opt-in via the resolver, not this flag).
static mut XML_LOAD_EXT_DTD_DEFAULT: c_int = 0;

#[unsafe(no_mangle)]
pub unsafe extern "C" fn __xmlLoadExtDtdDefaultValue() -> *mut c_void {
    record_call("__xmlLoadExtDtdDefaultValue");
    let addr = &raw mut XML_LOAD_EXT_DTD_DEFAULT;
    addr as *mut c_void
}

/// Bare `xmlParserVersion` data symbol — what consumers reading the
/// version global directly (rather than through the
/// `__xmlParserVersion()` accessor) link against.  `Sync` is asserted
/// by hand because `*const u8` isn't `Sync` by default; the pointer is
/// immutable and points to a `'static` byte literal, so reads from any
/// thread are safe.
#[repr(transparent)]
pub struct VersionPtr(*const u8);
unsafe impl Sync for VersionPtr {}

#[allow(non_upper_case_globals)]
#[unsafe(no_mangle)]
pub static xmlParserVersion: VersionPtr =
    VersionPtr(b"20913-sup-xml-compat\0".as_ptr());

// ── plain function stubs ─────────────────────────────────────────────────
//
// Auto-generated below from `target_symbols.txt`.  Hand-written
// implementations (see `parse.rs`, `tree.rs`, `attr.rs`, `ns.rs`,
// `serialize.rs`, `init.rs`, `error.rs`) take precedence — those
// symbols are filtered out of the stub set during regeneration.

