#!/usr/bin/env bash
# Regenerate stub modules from the live target_symbols list.
#
# Reads:   tests/abi-system/lxml/target_symbols.txt  (one symbol per line)
# Writes:  crates/compat/src/stubs.rs                  (functions)
# Updates: crates/compat/src/symbols.txt + symbols.ld  (version scripts)

set -euo pipefail
REPO="$(cd "$(dirname "$0")/../../.." && pwd)"
LIST="$REPO/tests/abi-system/lxml/target_symbols.txt"
STUBS_RS="$REPO/crates/compat/src/stubs.rs"
SYMS_TXT="$REPO/crates/compat/src/symbols.txt"
SYMS_LD="$REPO/crates/compat/src/symbols.ld"

# ── 1. stubs.rs ──────────────────────────────────────────────────────────
{
cat <<'HEADER'
//! Auto-generated stubs for libxml2 symbols that lxml (and other
//! consumers) reference at load time, but our shim doesn't yet
//! implement.
//!
//! Regenerated by `tests/abi-system/lxml/regen_stubs.sh` from
//! `tests/abi-system/lxml/target_symbols.txt`.  Do not edit by hand —
//! re-run the script after adding symbols to the canonical list.
//!
//! # Why every stub returns `*mut c_void`
//!
//! At load time, dyld only checks symbol *names*; signatures aren't
//! part of the linkage contract.  At runtime, the System V x86_64 /
//! AAPCS aarch64 calling conventions pass arguments in caller-saved
//! registers, so a no-arg stub can be called with any argument list
//! without corrupting state — the args just sit in registers we
//! ignore.  Return value goes in `rax`/`x0`, and `NULL` (0) is the
//! same bit pattern in every pointer or integer return type the
//! caller might interpret.
//!
//! Net effect: `import lxml` succeeds.  Any actual *use* of a stubbed
//! function gets NULL back and lxml's error-checking takes over —
//! typically raising a Python exception.

#![allow(non_snake_case)]

use std::os::raw::{c_int, c_void};
use std::ptr;

/// Diagnostic hook.  When `SUPXML_TRACE_STUBS` is set in the
/// environment, every stub call writes its name to stderr — useful
/// when a consumer crashes after calling an unimplemented function
/// and we want to know which one.
#[inline]
fn record_call(name: &'static str) {
    use std::sync::atomic::{AtomicI8, Ordering};
    static TRACE: AtomicI8 = AtomicI8::new(-1);
    let on = match TRACE.load(Ordering::Relaxed) {
        -1 => {
            let on = std::env::var_os("SUPXML_TRACE_STUBS").is_some();
            TRACE.store(if on { 1 } else { 0 }, Ordering::Relaxed);
            on
        }
        1 => true,
        _ => false,
    };
    if on {
        eprintln!("[stub] {name}");
    }
}

// Unused when every target symbol is already implemented (no stubs
// generated below) — that's the healthy state, not a problem.
#[allow(unused_macros)]
macro_rules! stub {
    ($name:ident) => {
        #[unsafe(no_mangle)]
        pub unsafe extern "C" fn $name() -> *mut c_void {
            record_call(stringify!($name));
            ptr::null_mut()
        }
    };
}

// ── thread-safe accessor functions (return pointer into mutable global) ──
//
// libxml2's globals.h has a pattern where each XMLPUBVAR global has a
// matching `__name()` accessor function.  When threading support is
// compiled in (the default on macOS / most distros), the bare global
// name expands to `(*(__name()))` — so the accessor is what shows up
// as an undefined symbol in consumer code.  We back each accessor
// with a zero-initialized storage slot of the right size.

/// libxml2 `_xmlSAXHandlerV1` (parser.h): 27 fn-ptr slots + `initialized: c_uint`
/// + 4 bytes natural padding.  We never read these fields — but our
/// storage must be large enough for callers to address them without
/// running past our allocation.
#[repr(C)]
#[derive(Copy, Clone)]
struct XmlSAXHandlerV1 {
    slots: [*mut c_void; 27],
    initialized: u32,
    _pad: u32,
}
const _: () = {
    assert!(std::mem::size_of::<XmlSAXHandlerV1>() == 224,
            "xmlSAXHandlerV1 must be 224 bytes (27*8 + 4 + 4 pad)");
};

static mut HTML_DEFAULT_SAX_HANDLER: XmlSAXHandlerV1 = XmlSAXHandlerV1 {
    slots: [ptr::null_mut(); 27],
    initialized: 0,
    _pad: 0,
};

#[unsafe(no_mangle)]
pub unsafe extern "C" fn __htmlDefaultSAXHandler() -> *mut c_void {
    record_call("__htmlDefaultSAXHandler");
    let addr = &raw mut HTML_DEFAULT_SAX_HANDLER;
    addr as *mut c_void
}

/// libxml2's `__xmlParserVersion()` returns `const xmlChar **`.
/// `xmlParserVersion` is a `const char *` global — the accessor
/// returns a pointer to that global.
static mut XML_PARSER_VERSION: *const u8 =
    b"20913-sup-xml-compat\0".as_ptr();

#[unsafe(no_mangle)]
pub unsafe extern "C" fn __xmlParserVersion() -> *mut c_void {
    record_call("__xmlParserVersion");
    let addr = &raw mut XML_PARSER_VERSION;
    addr as *mut c_void
}

/// `__xmlStructuredError()` returns `xmlStructuredErrorFunc *` —
/// a pointer to a function-pointer global.  We give it a single
/// nullable slot.
static mut XML_STRUCTURED_ERROR: *mut c_void = ptr::null_mut();

#[unsafe(no_mangle)]
pub unsafe extern "C" fn __xmlStructuredError() -> *mut c_void {
    record_call("__xmlStructuredError");
    let addr = &raw mut XML_STRUCTURED_ERROR;
    addr as *mut c_void
}

/// `__xmlStructuredErrorContext()` returns `void **` — a pointer to
/// a `void *` global slot.
static mut XML_STRUCTURED_ERROR_CONTEXT: *mut c_void = ptr::null_mut();

#[unsafe(no_mangle)]
pub unsafe extern "C" fn __xmlStructuredErrorContext() -> *mut c_void {
    record_call("__xmlStructuredErrorContext");
    let addr = &raw mut XML_STRUCTURED_ERROR_CONTEXT;
    addr as *mut c_void
}

/// libxml2's "generic" (printf-style) error reporter, twin of the
/// structured one above.  libxslt registers a handler here during
/// stylesheet parsing — without storage backing the slot, the
/// `xmlSetGenericErrorFunc(...)` call dereferences NULL.
static mut XML_GENERIC_ERROR: *mut c_void = ptr::null_mut();

#[unsafe(no_mangle)]
pub unsafe extern "C" fn __xmlGenericError() -> *mut c_void {
    record_call("__xmlGenericError");
    let addr = &raw mut XML_GENERIC_ERROR;
    addr as *mut c_void
}

/// Context pointer that pairs with the generic-error function above.
/// libxml2 hands it as the first argument to the error callback.
static mut XML_GENERIC_ERROR_CONTEXT: *mut c_void = ptr::null_mut();

#[unsafe(no_mangle)]
pub unsafe extern "C" fn __xmlGenericErrorContext() -> *mut c_void {
    record_call("__xmlGenericErrorContext");
    let addr = &raw mut XML_GENERIC_ERROR_CONTEXT;
    addr as *mut c_void
}

/// `__xmlIndentTreeOutput()` — pointer to the "indent tree output"
/// flag.  Default 1 (indent).  XML::LibXML reads this slot directly.
static mut XML_INDENT_TREE_OUTPUT: c_int = 1;

#[unsafe(no_mangle)]
pub unsafe extern "C" fn __xmlIndentTreeOutput() -> *mut c_void {
    record_call("__xmlIndentTreeOutput");
    let addr = &raw mut XML_INDENT_TREE_OUTPUT;
    addr as *mut c_void
}

/// `__xmlSaveNoEmptyTags()` — pointer to the "save no empty tags"
/// flag.  Default 0 (self-closing `<foo/>` form for empty elements).
static mut XML_SAVE_NO_EMPTY_TAGS: c_int = 0;

#[unsafe(no_mangle)]
pub unsafe extern "C" fn __xmlSaveNoEmptyTags() -> *mut c_void {
    record_call("__xmlSaveNoEmptyTags");
    let addr = &raw mut XML_SAVE_NO_EMPTY_TAGS;
    addr as *mut c_void
}

/// `__xmlDoValidityCheckingDefaultValue()` — pointer to the "validate
/// against DTD by default" flag.  Default 0 (no DTD validation unless
/// explicitly requested).
static mut XML_DO_VALIDITY_CHECKING_DEFAULT: c_int = 0;

#[unsafe(no_mangle)]
pub unsafe extern "C" fn __xmlDoValidityCheckingDefaultValue() -> *mut c_void {
    record_call("__xmlDoValidityCheckingDefaultValue");
    let addr = &raw mut XML_DO_VALIDITY_CHECKING_DEFAULT;
    addr as *mut c_void
}

/// `__xmlLoadExtDtdDefaultValue()` — pointer to the "load external
/// DTDs by default" flag.  Default 0 (XXE-safe; external DTD loading
/// is opt-in via the resolver, not this flag).
static mut XML_LOAD_EXT_DTD_DEFAULT: c_int = 0;

#[unsafe(no_mangle)]
pub unsafe extern "C" fn __xmlLoadExtDtdDefaultValue() -> *mut c_void {
    record_call("__xmlLoadExtDtdDefaultValue");
    let addr = &raw mut XML_LOAD_EXT_DTD_DEFAULT;
    addr as *mut c_void
}

/// Bare `xmlParserVersion` data symbol — what consumers reading the
/// version global directly (rather than through the
/// `__xmlParserVersion()` accessor) link against.  `Sync` is asserted
/// by hand because `*const u8` isn't `Sync` by default; the pointer is
/// immutable and points to a `'static` byte literal, so reads from any
/// thread are safe.
#[repr(transparent)]
pub struct VersionPtr(*const u8);
unsafe impl Sync for VersionPtr {}

#[allow(non_upper_case_globals)]
#[unsafe(no_mangle)]
pub static xmlParserVersion: VersionPtr =
    VersionPtr(b"20913-sup-xml-compat\0".as_ptr());

// ── plain function stubs ─────────────────────────────────────────────────
//
// Auto-generated below from `target_symbols.txt`.  Hand-written
// implementations (see `parse.rs`, `tree.rs`, `attr.rs`, `ns.rs`,
// `serialize.rs`, `init.rs`, `error.rs`) take precedence — those
// symbols are filtered out of the stub set during regeneration.

HEADER

# Collect symbols already implemented in hand-written modules.  Scan
# every .rs file in crates/compat/src/ EXCEPT stubs.rs — that file
# would chicken-and-egg itself (it's regenerated below from this same
# skip list).
SKIP="$(mktemp)"
trap 'rm -f "$SKIP"' EXIT
(
    # Scan both compat/src and tree/src: compat statically links the
    # tree crate and re-exports its `#[no_mangle]` symbols
    # (xmlStringText, xmlStringTextNoenc) into the cdylib, so they count
    # as implemented and must not be re-stubbed.
    # `find` rather than a hardcoded list so adding a new module
    # (strutil.rs, etc.) automatically gets its functions excluded
    # from the stub set.  Only count functions that are actually
    # exported as C symbols — those decorated with `#[no_mangle]` or
    # `#[unsafe(no_mangle)]`.  A bare `pub extern "C" fn foo()` is
    # still name-mangled by Rust, so it won't satisfy a dyld
    # reference to `_foo` and listing it in the exported-symbols
    # file makes the linker error out.  Common case where this
    # matters: the SAX `noop_*` callbacks in saxreplay.rs are used
    # only as Rust-internal function pointers handed to lxml, not as
    # exported C symbols.
    find "$REPO/crates/compat/src" "$REPO/crates/tree/src" \
         -maxdepth 1 -name '*.rs' ! -name 'stubs.rs' -print0 \
        | xargs -0 awk '
            # Attribute line carrying a C export.  Matches bare
            # #[no_mangle], #[unsafe(no_mangle)], and the
            # #[cfg_attr(feature = "cdylib-exports", unsafe(no_mangle))]
            # form most of the crate uses.  Anchored to `#[` so a comment
            # mentioning no_mangle does not arm.  If the fn declaration is
            # on the SAME line (e.g. `#[cfg_attr(...)] pub extern "C" fn
            # foo()`), extract it here; otherwise arm for the next line.
            /^[[:space:]]*#\[.*no_mangle/ {
                if ($0 ~ /extern[[:space:]]+"C"[[:space:]]+fn[[:space:]]+/ \
                    && match($0, /fn[[:space:]]+[A-Za-z_][A-Za-z0-9_]*/)) {
                    ident = substr($0, RSTART + 2, RLENGTH - 2);
                    sub(/^[[:space:]]+/, "", ident);
                    print ident;
                    armed = 0;
                    next;
                }
                armed = 1;
                next;
            }
            armed && /^[[:space:]]*pub[[:space:]]+(unsafe[[:space:]]+)?extern[[:space:]]+"C"[[:space:]]+fn[[:space:]]+/ {
                # Extract the identifier after `fn`.  Macro bodies
                # like `pub extern "C" fn $name()` match the outer
                # regex but contain a Rust macro placeholder we
                # cannot resolve at this scan level — those produce
                # no match here and we skip the line.
                if (match($0, /fn[[:space:]]+[A-Za-z_][A-Za-z0-9_]*/)) {
                    ident = substr($0, RSTART + 2, RLENGTH - 2);
                    sub(/^[[:space:]]+/, "", ident);
                    print ident;
                }
                armed = 0;
                next;
            }
            # Also count `pub static mut NAME` exports — libxml2 has
            # a number of fn-pointer globals (xmlMalloc, xmlFree,
            # xmlRealloc, etc.) that downstream consumers dereference
            # rather than call; those are expressed in Rust as
            # `pub static mut`, not `fn`.
            armed && /^[[:space:]]*pub[[:space:]]+static[[:space:]]+(mut[[:space:]]+)?[A-Za-z_][A-Za-z0-9_]*[[:space:]]*:/ {
                match($0, /(static[[:space:]]+(mut[[:space:]]+)?)[A-Za-z_][A-Za-z0-9_]*/);
                # The match starts at "static "; advance past it to the identifier.
                seg = substr($0, RSTART, RLENGTH);
                sub(/^static[[:space:]]+(mut[[:space:]]+)?/, "", seg);
                print seg;
                armed = 0;
                next;
            }
            # Also pick up declarative macro invocations like
            # `xslt_null_stub!(name);` — they expand to a
            # #[no_mangle] extern "C" fn under the same identifier,
            # so listing them in stubs.rs would collide at link time.
            # Match any `*_stub!(IDENT);` macro call regardless of the
            # macro prefix (covers xslt_null_stub, xslt_minus_one_stub,
            # xslt_void_stub, and any future stub-family macros).
            /^[[:space:]]*[A-Za-z_][A-Za-z0-9_]*_stub![[:space:]]*\([[:space:]]*[A-Za-z_][A-Za-z0-9_]*[[:space:]]*\)[[:space:]]*;[[:space:]]*$/ {
                match($0, /\([[:space:]]*[A-Za-z_][A-Za-z0-9_]*[[:space:]]*\)/);
                seg = substr($0, RSTART, RLENGTH);
                gsub(/[()[:space:]]/, "", seg);
                print seg;
                next;
            }
            # Any non-blank, non-attribute line cancels the arming —
            # we only credit a #[no_mangle] that directly precedes
            # the fn / static declaration.
            /^[[:space:]]*$/        { next }
            /^[[:space:]]*#\[/      { next }
            /^[[:space:]]*\/\//     { next }
                                    { armed = 0 }
        '
    # Accessor functions + data symbols emitted manually in the header
    # above.  stubs.rs is excluded from the source scan, so anything
    # the heredoc defines must be named here to land in symbols.txt.
    printf '%s\n' __htmlDefaultSAXHandler __xmlParserVersion \
                  __xmlStructuredError __xmlStructuredErrorContext \
                  __xmlGenericError    __xmlGenericErrorContext \
                  __xmlIndentTreeOutput __xmlSaveNoEmptyTags \
                  __xmlDoValidityCheckingDefaultValue \
                  __xmlLoadExtDtdDefaultValue xmlParserVersion
) | sort -u > "$SKIP"

# Generate `stub!(name);` lines for symbols not in the skip set.
# Both files are sorted; `comm -23` lists lines in $LIST that are not
# in $SKIP — exactly what we want.
comm -23 "$LIST" "$SKIP" | sed 's/^/stub!(/; s/$/);/'
} > "$STUBS_RS"

# Emit a summary line for build logs.
# grep -c exits 1 when no matches — perfectly normal when every
# symbol is covered by hand-written code.  `|| true` swallows that
# nonzero exit so `set -e` doesn't abort the rest of the script.
N_STUBS=$(grep -c "^stub!" "$STUBS_RS" || true)
echo "regenerated $STUBS_RS ($N_STUBS stub! invocations + accessors)"

# ── 2. symbols.txt (macOS exported symbols list) ─────────────────────────
# Union of: hand-implemented symbols + accessor functions + every
# entry from target_symbols.txt.  Each name gets a leading underscore.
{
    cat "$SKIP"
    cat "$LIST"
} | sort -u | sed 's/^/_/' > "$SYMS_TXT"
N_SYM=$(wc -l < "$SYMS_TXT")
echo "regenerated $SYMS_TXT ($N_SYM symbols)"

# ── 3. symbols.ld (Linux version script) ─────────────────────────────────
{
    echo "/* Auto-generated by tests/abi-system/lxml/regen_stubs.sh"
    echo " * Source of truth: target_symbols.txt + crates/compat/src/*.rs */"
    echo "SUPXML_COMPAT_2 {"
    echo "    global:"
    sed 's/^_//' "$SYMS_TXT" | sort -u | awk '{ print "        " $0 ";" }'
    echo "    local:"
    echo "        *;"
    echo "};"
} > "$SYMS_LD"
echo "regenerated $SYMS_LD"
